[[services]]
name = "backend"
source = "server"

[services.build]
builder = "NIXPACKS"

[services.deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]  
name = "frontend"
source = "client"

[services.build]
builder = "NIXPACKS"

[services.deploy]
startCommand = "npm run build && npx serve -s build -p $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10